#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>

int main(int argc,char **argv) {

	FILE *fff;
	unsigned char buff[16];
	int j,i,k;

	if (argc<1) {
		printf("Usage: font2include fontfilename\n\n");
		exit(5);
	}

	if ((fff=fopen(argv[1],"r"))==NULL) {
		printf("Error!  %s does not exist.\n\n",argv[1]);
		exit(7);
	}

	/* FIXME: verify we are a 4k font file */

	printf ("\t/* Generated by font2include.c */\n");
	printf ("unsigned char default_font[256][16] = {\n");
	j=0;

	while ((j<256) && (!feof(fff))) {

		fread(buff,1,16,fff);

		if (isprint(j)) {
			printf("/* '%c' */\n",j);
		}
		else {
			printf("/* 0x%x */\n",j);
		}

		printf("{\n");
		for(i=0;i<16;i++) {
			printf("\t0x%02x,\t",buff[i]);
			printf("/* ");
			for(k=0;k<8;k++) {
				if (buff[i]&(1<<(7-k))) {
					printf("*");
				}
				else {
					printf(" ");
				}
			}
			printf(" */\n");
		}

		printf("}");
		if (j<256) printf(",");
		printf("\n");
		j++;
	}
	printf("};\n");
	fclose(fff);

	return 0;
}
